"""
AML Policy Composer
Reads JSON policy modules and assembles a complete AML/CFT/CPF policy
based on user input.
"""

import json
import os
from pathlib import Path


def load_modules(modules_dir="policy_modules"):
    """
    Load all module JSON files from the policy_modules directory.
    Returns a list of module dictionaries sorted by section_number.
    """
    modules = []
    modules_path = Path(modules_dir)
    
    if not modules_path.exists():
        raise FileNotFoundError(f"Modules directory not found: {modules_dir}")
    
    json_files = sorted(modules_path.glob("*.json"))
    
    for json_file in json_files:
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                module = json.load(f)
                modules.append(module)
        except json.JSONDecodeError as e:
            raise ValueError(f"Invalid JSON in {json_file.name}: {e}")
    
    modules.sort(key=lambda m: m.get("section_number", 999))
    
    return modules


def evaluate_condition(condition, user_answers):
    """
    Evaluate whether a condition is met based on user answers.
    """
    if not condition:
        return True
    
    for key, allowed_values in condition.items():
        user_value = user_answers.get(key)
        
        if user_value is None:
            return False
        
        if isinstance(user_value, list):
            if not any(v in allowed_values for v in user_value):
                return False
        else:
            if user_value not in allowed_values:
                return False
    
    return True


def should_include_block(block, user_answers):
    """
    Determine whether a content block should be included in the policy.
    """
    if block.get("always_include", False):
        return True
    
    if "include_if" in block:
        return evaluate_condition(block["include_if"], user_answers)
    
    if "include_if_not" in block:
        return not evaluate_condition(block["include_if_not"], user_answers)
    
    return False


def substitute_variables(text, user_answers):
    """
    Replace {variable_name} placeholders in text with user-provided values.
    """
    substitutions = {
        "{firm_name}": user_answers.get("firm_name", "[Firm Name]"),
        "{registered_state}": user_answers.get("registered_state", "[State]"),
    }
    
    services = user_answers.get("services_offered", [])
    business_specifics = user_answers.get("business_model_specifics", [])
    all_services = services + business_specifics
    
    if all_services:
        services_text = ", ".join(all_services)
    else:
        services_text = "virtual digital asset services as specified in applicable notifications"
    
    substitutions["{applicable_services}"] = services_text
    
    assets = user_answers.get("asset_coverage", [])
    if assets:
        assets_text = ", ".join(assets)
    else:
        assets_text = "virtual digital assets"
    
    substitutions["{applicable_assets}"] = assets_text
    substitutions["{applicable_assets_risk_text}"] = (
        f"the risk profile of the following asset categories offered by the Company: {assets_text}"
    )
    substitutions["{applicable_services_risk_text}"] = (
        f"the risk profile of the following services offered by the Company: {services_text}"
    )
    
    for placeholder, value in substitutions.items():
        text = text.replace(placeholder, value)
    
    return text


def compose_policy(user_answers, modules_dir="policy_modules"):
    """
    Main function: compose the complete policy from user answers.
    Returns the assembled Markdown text.
    """
    modules = load_modules(modules_dir)
    
    policy_parts = []
    
    firm_name = user_answers.get("firm_name", "[Firm Name]")
    header = f"# Anti-Money Laundering, Counter-Financing of Terrorism, and Counter-Proliferation Financing Policy\n\n"
    header += f"**Entity:** {firm_name}\n\n"
    header += f"**Generated by:** AML Policy Framework Builder for Indian VDA SPs (v0.1)\n\n"
    header += f"---\n\n"
    policy_parts.append(header)
    
    for module in modules:
        module_text_parts = []
        
        for block in module.get("content_blocks", []):
            if should_include_block(block, user_answers):
                block_text = block.get("text", "")
                block_text = substitute_variables(block_text, user_answers)
                module_text_parts.append(block_text)
        
        if module_text_parts:
            policy_parts.append("".join(module_text_parts))
            policy_parts.append("\n\n")
    
    footer = "\n---\n\n"
    footer += "## Methodology Note\n\n"
    footer += "This document was generated by the AML Policy Framework Builder for Indian VDA SPs (v0.1), "
    footer += "an open-source structured framework for drafting AML/CFT/CPF policies for Indian Virtual Digital Asset Service Providers. "
    footer += "The document represents a starting framework calibrated to the firm profile provided, "
    footer += "anchored to the FIU-IND AML & CFT Guidelines for Reporting Entities Providing Services Related to Virtual Digital Assets dated January 8, 2026, "
    footer += "the Prevention of Money Laundering Act, 2002, and the Prevention of Money-Laundering (Maintenance of Records) Rules, 2005.\n\n"
    footer += "**This document is not legal advice, is not a finished policy, and is not a substitute for qualified legal counsel.** "
    footer += "The Reporting Entity must customise this framework to its specific circumstances, validate every provision against the current text of applicable regulations, "
    footer += "obtain qualified Indian legal review before adoption, and ensure that operational implementation of every requirement in this Policy is in place before relying on the Policy in any regulatory context.\n\n"
    policy_parts.append(footer)
    
    return "".join(policy_parts)


if __name__ == "__main__":
    sample_answers = {
        "firm_name": "Acme Crypto Exchange Pvt Ltd",
        "registered_state": "Maharashtra",
        "year_founded": 2021,
        "annual_transaction_volume": "₹100-500 cr",
        "customer_base": "Both retail and institutional",
        "active_user_count": "10,000-50,000",
        "asset_coverage": ["BTC", "ETH", "stablecoins", "major altcoins"],
        "services_offered": ["Spot trading", "Custody"],
        "cross_border_element": "Indian customers + NRI",
        "compliance_staffing": "Small team 2-5",
        "board_composition": "Founder-led",
        "tech_stack": ["Sumsub", "Chainalysis"],
        "group_structure": "Standalone",
        "existing_policy_status": "None",
        "business_model_specifics": ["Spot trading"],
    }
    
    print("Generating sample policy...\n")
    policy = compose_policy(sample_answers)
    
    output_path = Path("test_output.md")
    output_path.write_text(policy, encoding="utf-8")
    
    print(f"Sample policy generated: {output_path.absolute()}")
    print(f"Total length: {len(policy):,} characters")
    print(f"Approximate word count: {len(policy.split()):,} words")
    print(f"\nFirst 500 characters:\n")
    print(policy[:500])